### ISSUE TITLE
ABS mouse movements do not work

### ISSUE THREAD

**Issue by glenntanner3** [stjeong/rasp_vusb#1]
After changing to version 0 which works, under Linux, only keyboard and relative mouse movements work. I cannot pinpoint a reason for this in the code. There are no code changes between version 0 and 2 which relate to the mouse/keyboard control thus I believe this to still be broken.
Client: Arch Linux, Mono V.6.4.0
Server: Raspberry pi 0 w 1.1
Host: Fedora Linux

**Comment by stjeong** [comment]
Which means, you connected your raspberry pi to Fedora Linux PC?

Well, I did test it only to Windows PC. Would you test it with Windows PC? Currently, I don't work with Raspberry PI device anymore. (For testing, I have to brush my old RP off)

**Comment by glenntanner3** [comment]
I work with a team in India that recommended this software and I believe
they have it connected to windows host. Additionally I found this post
https://stackoverflow.com/questions/57987969/raspberry-pi-zero-turned-into-a-virtual-mouse-is-not-working-properly-on-windo
so
I believe your software works, with a windows host.

Thank you,
Glenn Tanner

**Comment by glenntanner3** [comment]
So i dumped the USB for my mouse and the PI from my Arch Linux system running KDE plasma today. Hope this info helps. Also noticed that your program always sends 2 USB commands and is 2 bytes short of the real device.
**wheel**
```
#w10
001:004:000:STREAM             1578059841.233886
 03 00 00 00 00 F6
001:004:000:STREAM             1578059841.234587
 03 00 00 00 00 00
#w-10
001:004:000:STREAM             1578060121.385859
 03 00 00 00 00 0A
001:004:000:STREAM             1578060121.387041
 03 00 00 00 00 00
#w1
001:004:000:STREAM             1578060285.943381
 03 00 00 00 00 FF
001:004:000:STREAM             1578060285.944214
 03 00 00 00 00 00
#w-1
001:004:000:STREAM             1578060294.532116
 03 00 00 00 00 01
001:004:000:STREAM             1578060294.533277
 03 00 00 00 00 00

#wheel up 
003:002:001:STREAM             1578059948.891956
 03 00 00 00 00 01 00
#wheel down
003:002:001:STREAM             1578059951.397969
 03 00 00 00 00 FF 00
```
**movement**
```
#+100 +100
001:004:000:STREAM             1578059831.889890
 02 00 64 64
001:004:000:STREAM             1578059831.890810
 02 00 00 00
#1500 800
001:004:000:STREAM             1578059838.690926
 03 DC 05 20 03 00
001:004:000:STREAM             1578059838.691949
 03 00 00 00 00 00
#real mouse move down-right
003:002:001:STREAM             1578059324.642526
 03 00 01 D0 FF 00 00
003:002:001:STREAM             1578059324.646556
 03 00 00 F0 FF 00 00
003:002:001:STREAM             1578059324.664544
 03 00 04 C0 FF 00 00
003:002:001:STREAM             1578059324.668554
 03 00 01 F0 FF 00 00
003:002:001:STREAM             1578059324.674596
 03 00 03 D0 FF 00 00
```

**Comment by stjeong** [comment]
Thanks for your feedback. :)

I can't afford to handle the difference nowadays. Someday, I'll check it. (Raspberry PI is out of my interests.)
