### ISSUE TITLE
API docs/C++ DLL

### ISSUE THREAD

**Issue by rlewkowicz** [stjeong/rasp_vusb#13]
I'm going to go dig on that C# code. I've not written C#, so I just have to go figure out what it's doing. It would be cool to even have "api" docs. I see the TCP socket connect. Do I have to use ssl? Even if it was just a sudo code simplified common language document that is just like:
```
1: tcp connect to ip
2: send bytes
```
Just so I don't have to poke and prod so much. I wanted to try this: https://github.com/3F/DllExport

It looks like you apply some "decorators" (this is what it's called in python) and it can allow you to call methods from c++. This requires sln files though. I guess cs proj is "old"? I just don't know enough. 

I'll contribute something if I put anything coherent together.

**Comment by rlewkowicz** [comment]
I'll leave this open as the Readme says suggestions are welcome. I'd still love a C++ dll, but at this time I found a less cumbersome implementation that I can build a rest interface around.

**Comment by rlewkowicz** [comment]
So I lied. The http overhead is too slow. I'm looking at ecal now. I think it's less of a lift for me to integrate it into the c++ server than it is to do sockets and all that.

**Comment by stjeong** [comment]
Thanks. Like I said, PR is always welcome. :) "suggestions" means "PR"

**Comment by rlewkowicz** [comment]
fair enough :P I'll try to put together something respectable enough to merge
