### ISSUE TITLE
Writing to the hid_tester input screen doesnt do anything

### ISSUE THREAD

**Issue by narbat** [stjeong/rasp_vusb#14]
Hi

I read your articles about the topic and followed to the point where you type the text in hid_tester input screen. However when I type to the input screen nothing happens. Do you have any idea why it doesn’t work?

**Comment by stjeong** [comment]
Sorry for late response. And... I'm sorry again that I can't answer your question. At that time, it worked, but now, I can't test it because I don't have the device anymore.

You have to debug yourself with the source code. All of the resources are opened publicly in my blog.
