### ISSUE TITLE
Increase hold of left click

### ISSUE THREAD

**Issue by rdavini** [stjeong/rasp_vusb#16]
Hello, thank you for making this project open source. I ran succefully in a raspberry pi zero w. However, I need to hold the left click for around 3-4 seconds. Could you please give a general instruction on how I can achieve this?

I was trying to add a sleep at the end of MouseDevice::SendRelative function inside the rasp_vusb_server but I'm having some trouble building this project. Could you please inform If I'm in the right path.

**Comment by stjeong** [comment]
First, sorry to answer without running the code. 

I remember that... mouse click is divided into "DOWN" and "UP". Maybe... this code,

https://github.com/stjeong/rasp_vusb/blob/9e2cc6834757e337d78a6f158ecc6883fa2c98eb/InputController/MouseDevice.cs#L111

will return buffer for left-click "DOWN".

Again maybe, this code,

https://github.com/stjeong/rasp_vusb/blob/9e2cc6834757e337d78a6f158ecc6883fa2c98eb/InputController/MouseDevice.cs#L35

will append buffer for "UP".

**Comment by rdavini** [comment]
Ok thx alot.
