### ISSUE TITLE
[Question] Why send always a 1 in the Modifier Key byte

### ISSUE THREAD

**Issue by carlosfvp** [stjeong/rasp_vusb#17]
https://github.com/stjeong/rasp_vusb/blob/master/rasp_vusb_server/KeyboardDevice.cpp#L32

@stjeong  Is there a special reason that you need to send a 1 in the modifier key byte?

I am capturing USB "packets" with Wireshark and I see my regular keyboard sends a packet without the number 1 at the begining.

Of course If I remove the 1 from the code, recompile and run, the RaspberryPi keyboard stops working.

I was trying to understand this project following this structure but it looks like I am missing something.

https://wiki.osdev.org/USB_Human_Interface_Devices "USB keyboard" section

Would you mind sharing the reason behind this?

**Comment by carlosfvp** [comment]
When the report descriptor implements more than 1 device, the structure is different?

**Comment by stjeong** [comment]
You're right. :)
However, it's not he modifier key byte, but report_id. 

I didn't use struct for keyboard. Instead, you can find the field for mouse at https://github.com/stjeong/rasp_vusb/blob/master/rasp_vusb_server/MouseDevice.h#L19

For example, you can see the struct for keyboard at https://www.sysnet.pe.kr/2/0/11363#keyboard_report

I used HID Report Descriptors like this, (refer to: https://www.sysnet.pe.kr/2/0/11363#report_desc, https://www.sysnet.pe.kr/2/0/11369#reportid)

```
05, 01, USAGE_PAGE (Generic Desktop)
09, 06, USAGE (Keyboard)
a1, 01, COLLECTION (Application)
85, 01,     REPORT_ID (1)
05, 07      USAGE_PAGE (Keyboard)
19, e0      USAGE_MINIMUM (Keyboard LeftControl)
29, e7      USAGE_MINIMUM (Keyboard Right GUI)
15, 00      LOGICAL_MINIMUM (0)
...[omitted for brevity]...
C0      END_COLLECTION
05, 01  USAGE_PAGE (Generic Desktop)
09, 02  USAGE (Mouse)
a1, 01  COLLECTION (Application)
09, 01      USAGE (Pointer)
a1, 00      COLLECTION (Physical)
85, 02          REPORT_ID (2)
05, 09          USAGE_PAGE (Button)
...[omitted for brevity]...
C0          END_COLLECTION
C0      END_COLLECTION
````

So, report_id == 1 for keyboard, report_id == 2 for mouse (relative position), and report_id == 3 for mouse (absolute position and wheel)
