### ISSUE TITLE
Compatible with Raspberry Pi Zero 2

### ISSUE THREAD

**Issue by carlosfvp** [stjeong/rasp_vusb#18]
Hi,

Is the triple-usb-device script is compatible with Zero 2 model?

I've just ran throught all the steps but I can't get to display device in Windows machine.

I have a Zero (1) and it works perfect there, so I'm suspecting a compatibility issue with Zero 2.

I hope you can guide me through.

Thank you.

**Comment by stjeong** [comment]
I'm not sure about that. I don't have Zero 2 device.

**Comment by carlosfvp** [comment]
Sorry to insist but where would you start to debug this? so I can provide some extra information.

**Comment by carlosfvp** [comment]
Nevermind, the issue was the mini-usb cable. Apparently all cables I was using on the Zero 2 are not capable to use the Raspberry as usb gadget.
