### ISSUE TITLE
InputController.exe only searches for 192.168.178.255

### ISSUE THREAD

**Issue by olivermarx** [stjeong/rasp_vusb#3]
Hi,

when running InputController.exe on my windows machine, it only searches for 192.168.178.255...whereas the Pi0 has 192.168.178.145...can I pass the correct IP as a parameter ?

thx
Oliver

**Comment by stjeong** [comment]
InputController uses UDP broadcasting to find Raspberry PI zero device on the same network, so the IP address shows xxx.xxx.xxx.255.

Your PI device seems not to get UDP broadcast packet. In that case, you can just connect using UsbController.Connect method.
