### ISSUE TITLE
Overall working flow

### ISSUE THREAD

**Issue by DarkFighterLuke** [stjeong/rasp_vusb#5]
Hello, I'm very surprised to find a project which seems to emulate both mouse and keyboard at the same time.
Anyway, I think it would be very useful to add to the readme file an overall working flow to describe how basically works your project.

**Comment by stjeong** [comment]
Would you ...? :)

In fact, I've written 5 articles about this in Korean.

Raspberry Pi Zero(OTG)를 다른 컴퓨터에 연결해 가상 키보드로 쓰는 방법
; https://www.sysnet.pe.kr/2/0/11354

Raspberry Pi Zero(OTG)를 다른 컴퓨터에 연결해 가상 마우스로 쓰는 방법
; https://www.sysnet.pe.kr/2/0/11355

Raspberry Pi Zero(OTG)를 다른 컴퓨터에 연결해 가상 마우스로 쓰는 방법 (절대 좌표)
; https://www.sysnet.pe.kr/2/0/11355

Raspberry Pi Zero(OTG)를 다른 컴퓨터에 연결해 가상 키보드 및 마우스로 쓰는 방법 (절대 좌표, 상대 좌표, 휠)
; https://www.sysnet.pe.kr/2/0/11369

Raspberry Pi Zero(OTG)를 다른 컴퓨터에 연결해 가상 마우스 + 키보드로 쓰는 방법
; https://www.sysnet.pe.kr/2/0/11356

I couldn't try to translate this articles into English. (I'm Korean, and my English is very poor. ) Someday... well... I can't promise, but I will.... :)
