### ISSUE TITLE
Question: If i wanted to directly comunicate to the pi with mouse input with Python how would I do that

### ISSUE THREAD

**Issue by The-Drobe** [stjeong/rasp_vusb#6]
I was wondering if it is at all possible to directly communicate with the pi via a python script instead of using the input controller exe I only want to do mouse movement and that is it and have it send the mouse position as absolute 

Thanks for your time

**Comment by stjeong** [comment]
With Python, you can communicate with rasp_vusb_server running on PI device.

The communication is based on just SSL socket, referred to this receiver-side code at

- https://github.com/stjeong/rasp_vusb/blob/master/rasp_vusb_server/VUsbServer.cpp#L46
- https://github.com/stjeong/rasp_vusb/blob/master/rasp_vusb_server/MouseDevice.cpp

or, sender-side code at

- https://github.com/stjeong/rasp_vusb/blob/master/InputController/MouseDevice.cs
- https://github.com/stjeong/rasp_vusb/blob/master/InputController/UsbController.cs

I'm poor at python, so can't include source codes at this repo, but, I think you can do it. :) I'm looking forward to your PR.

**Comment by The-Drobe** [comment]
Stupid question but to use ssl I require the private.key and the certchain.pem where in your code do you generate them or keep them

**Comment by The-Drobe** [comment]
another question is it at all possible to tell me the format of the request to the server in the rasberry pi

**Comment by stjeong** [comment]
> Stupid question but to use ssl I require the private.key and the certchain.pem where in your code do you generate them or keep them

You can find those files at https://github.com/stjeong/rasp_vusb/tree/master/script

- key.pem
- test.pem

These files are copied into /share by deploy_with_pscp.bat, and load by VUsbServer::init_openssl function (https://github.com/stjeong/rasp_vusb/blob/master/rasp_vusb_server/VUsbServer.cpp#L192)

**Comment by stjeong** [comment]
> another question is it at all possible to tell me the format of the request to the server in the rasberry pi

Well... the packet format is explained in C# code. :)

You just need to convert "ConvertToMouseCommand" method into Python Language. (https://github.com/stjeong/rasp_vusb/blob/master/InputController/MouseDevice.cs#L11)

(Sorry for that I didn't documented.)

**Comment by Johsei** [comment]
Hey guys, @The-Drobe have you been successful with your python implementation by any chance? Thank you!

**Comment by Johsei** [comment]
@stjeong Or would it be easyer to do this in C++ on the Raspberry? 
Is there a function i could call on the Raspberry to move the mouse of my connected Windows PC, maybe like SendRelative() in MouseDevice? 

Thanks for your help, I'm sorry that as a beginner I don't really gain understanding of your code.

**Comment by stjeong** [comment]
You can do that in C++ on the Raspberry PI directly. "MouseDevice" code within InputController is just for sending "mouse data" to rasp_vusb_server running on Raspberry PI.

So, you can use socket to send the "mouse data" from your program to rasp_vusb_sverver in C++ instead of C#.

If you run your program on Raspberry PI, you can just write "mouse data" to virtual device "/dev/hidg0" directly, no need to use socket, and no need to use rasp_vusb_server.
