### ISSUE TITLE
Fail in "Create Mouse/Keyboard USB gadgets"

### ISSUE THREAD

**Issue by LReiz** [stjeong/rasp_vusb#8]
Hey, 
I really liked the project and it is definitely what I was searching for. But when I try to test it, Mouse and Keyboard don't work. I followed all steps in README. I'm also testing it on Windows. I think it has to do with a fail in creating the gadgets : "loaded failed failed    Create Mouse/Keyboard USB gadgets" (as it shows in the following picture)

![Screenshot_2](https://user-images.githubusercontent.com/50057281/119213479-ba189a00-ba95-11eb-9371-f28aa13fcaa1.png)

Is there a documentation for these errors where I can check?
Thanks in advance :)

**Comment by stjeong** [comment]
Well... it shows "loaded active running", which means maybe it was already installed. (Maybe you did it twice)

**Comment by stjeong** [comment]
Expired. (Please open new issue later)
