### ISSUE TITLE
Run by Pi

### ISSUE THREAD

**Issue by mayerf97** [stjeong/rasp_vusb#9]
Hello, Im currently trying to setup this project. 
My problem is, that i dont unterstand, how to give the Pi the parameters to move the Mouse. 
Is there any way, to controle the windowsmachine only by using scripts on the pi?
Sry my C-Language knowledge isnt that good.

I think the commands for the USB output is written into /dev/hidg0
But i cant get the project run for reverse engineering what this file needs to function

I guess something like 0x07...

**Comment by stjeong** [comment]
Right, commands are written to /dev/hidg0.

You can check how to write to /dev/hidg0 as follows,

https://github.com/stjeong/rasp_vusb/blob/master/rasp_vusb_server/MouseDevice.cpp

Without any helper, you can write only with this source code,

```
mouse_abs_report_t item;
item.report_id = 3; // 3 == absolute(mouse), 2 = relative(mouse)
item.x = 50;
item.y = 60;
item.wheel = 0;
write(fd, &item, sizeof(mouse_abs_report_t));  // fd == handle to the device "/dev/hidg0"
```

**Comment by michaelmano** [comment]
Id also be really interested in this. I want to set up a web server on the PI and send X and Y coords and it then moves the mouse to those locations and clicks

I've got no idea where to start with moving the mouse on the PI.

Obviously you dont just write 
```
mouse_abs_report_t item;
item.report_id = 3; // 3 == absolute(mouse), 2 = relative(mouse)
item.x = 50;
item.y = 60;
item.wheel = 0;
write(fd, &item, sizeof(mouse_abs_report_t)); // fd == handle to the device "/dev/hidg0"
```
Into bash. Where would I go about starting with this?

Also Thanks so much for this!

**Comment by stjeong** [comment]
I'm not good at linux bash script. I just can tell you data structure which is used for moving mouse.

`
[1byte][2byte][2byte][1byte]
`

1) first byte: 3 == absolute position
2) 2byte: x-position
3) 2byte: y-position
4) 1byte: wheel data (commonly 0)

Just write data with this format to /dev/hidg0 file, then it will work.

If succeded, please send PR to this repo.

**Comment by michaelmano** [comment]
Thanks for that, Ive found some more info. I will def make a pull request once finished.
You would not happen to know what to send for a right click would you?
```
sudo echo "\0\x10\0" >> /dev/hidg0 # x axis direction
sudo echo "\0\0\x10" >> /dev/hidg0 # y axis direction to move
sudo echo "\x1\0\0" >> /dev/hidg0 # left click
sudo echo "\0\0\0" >> /dev/hidg0 # release
```

**Comment by stjeong** [comment]
```
sudo echo "\x1\0\0" >> /dev/hidg0 # left click
sudo echo "\0\0\0" >> /dev/hidg0 # release
```

Is that working really? Do the code click left button?

Well... for clicking buttons and moving mouse relatively, you have to specify report_desc_id as 2 (code:  https://github.com/stjeong/rasp_vusb/blob/master/rasp_vusb_server/MouseDevice.cpp#L13)

So the format is,

`
[1byte][1byte][1byte][1byte]
`

1. first byte: 2 == relative position or button click (report_descriptor_id)
2. 1byte: button (left: 1, middle: 2, right: 4)
3. 1byte: x-position (relative)
4. 1byte: y-position (relative)

By your code for clicking mouse button, next code will work.

```
sudo echo "\x2\x1\0\0" >> /dev/hidg0 # left click
sudo echo "\x2\0\0\0" >> /dev/hidg0 # release

sudo echo "\x2\x2\0\0" >> /dev/hidg0 # middle click
sudo echo "\x2\0\0\0" >> /dev/hidg0 # release

sudo echo "\x2\x4\0\0" >> /dev/hidg0 # right click
sudo echo "\x2\0\0\0" >> /dev/hidg0 # release
```

**Comment by mayerf97** [comment]
Hello and thanks for your answers!!
I wrote a simple python-script 

with open('/dev/hidg0, 'rb+'') as fd:
    fd.write("\x03\x10\x20\x00")
    fd.write("\x03\x00\x00\x00")

And that moves the mouse

But i cant find out how to tell the script the pixel i want the mouse to be poition i want. For example [500px; 330px]

Im not able to import the InputController.cpp to VS-Code because i have literly 0 knowledge about C stuff^^ 
But if we knew how the programm converts those numbers (like the README example), we would know how the input has to look like

Or if we hab a dokumentation how to use the hidg0 properly. But i cant find anything

**Comment by stjeong** [comment]
Well... first byte 0x03 at fd.write means it follows mouse_abs_report_t format.

So, you have to write 6bytes at fd.write. (refer to the comment https://github.com/stjeong/rasp_vusb/issues/9#issuecomment-858379451)

```
with open('/dev/hidg0, 'rb+'') as fd:

// this is pseudo-code (not exactly python)
var x = \x10\x00
var y = \x20\x00

fd.write("\x03\" + x + y "\x20\x00")
fd.write("\x03\0x0\0x0\0x0\0x0\x00")
```

For determining pixel position, you have to know the resolution of your monitor. How to calculate the position is written at https://github.com/stjeong/rasp_vusb#how-to-test like this,

```
x = 50 * 32767 / 1920 = 853
y = 100 * 32767 / 1080 = 3033
```

**Comment by michaelmano** [comment]
One last question from me! Thanks again for replying, I've learnt so much about HID from this repo alone.

The below:
```
x = 50 * 32767 / 1920 = 853
y = 100 * 32767 / 1080 = 3033
```
If you were to convert `853` into a byte string. How would I go about doing that? it's not hex is it? e.g. `853 = 0x355` and `3033 = 0xBD9`? 

I know this is a stupid question, but I cant figure out what to even search for or where to ask it.

**Comment by stjeong** [comment]
If you want to set mouse position (x = 50,  y =100), you can code as follows,

```
with open('/dev/hidg0, 'rb+'') as fd:

fd.write("\x03\x55\0x03\0xd9\x0b\x00")
fd.write("\x03\0x0\0x0\0x0\0x0\x00")
```

**Comment by mayerf97** [comment]
But how do you convert `853 3033` to `\x03\x55\0x03\0xd9\x0b\x00` ?
`853` is `\x55\0x03`  and
`3033` is `\0xd9\x0b` 
But `\0xd9` is a hex number and `\x0b` is a character constant represented by a hex number.
Im so sorry but i really dont get it...

**Comment by stjeong** [comment]
This site will help you.

https://stackoverflow.com/

**Comment by mayerf97** [comment]
> If you want to set mouse position (x = 50, y =100), you can code as follows,
> 
> ```
> with open('/dev/hidg0, 'rb+'') as fd:
> 
> fd.write("\x03\x55\0x03\0xd9\x0b\x00")
> fd.write("\x03\0x0\0x0\0x0\0x0\x00")
> ```

I mean, this is just wrong. It doesnt place the cursor at 50 100.

**Comment by mayerf97** [comment]
Calculate with

> x = 50 * 32767 / 1920 = 853
y = 100 * 32767 / 1080 = 3033

`fd.write("\x03\x55\x03\xd9\x0b\x00") `
` #_____________|x-koord|y-koord|_____`
`fd.write("\x03\x00\x00\x00\x00\x00")`

initialate : \x03 and then

In Hex. Fill with Zeros from the largest Index. 
0xBD9 --> 0x0BD9
Order: \x10\x32 
y-position): \xD9\x0B
